### ISSUE TITLE
Install.sh not working

### ISSUE THREAD

**Issue by j-clap** [twosigma/Halite-II#924]
Upon placing install instructions on install.sh, bot compiles but does not have the package installed.

installation instructions were:

pip3 install delorean

code contained:

from delorean import Delorean
EST = "US/Eastern"
d = Delorean(timezone=EST)

This causes the bot to error out.

**Comment by lidavidm** [comment]
Do you have an example of this bot? My suspicion is that `pip install` tries to install to the global `site-packages`, and so you need some flags to install in the bot directory, as was done in #607: `python3 -m pip install --system pandas -t . --no-deps` (this could/should be documented better).

**Comment by lidavidm** [comment]
Yeah, what's happening is that `delorean` is getting installed in `/home/bot_compilation/.local/lib/python3.5/site-packages`. Also, as a side effect of changing the default to python 3.6, we should use `python3.6 -m pip` instead of `pip3`.

**Comment by lidavidm** [comment]
So this is the command that we should document as being used:

```
python3.6 -m pip install --system -t . <package>
```

**Comment by j-clap** [comment]
That doesn't work also:


Hello j-clap,   We are sorry to inform you that your recently submitted Halite bot did not compile. We detected that this bot was written with Other. Visit your profile page to learn more.   Here is the error we detected while trying to compile your bot:   Your bot caused unexpected behavior in our servers. If you cannot figure out why this happened, please email us at halite@halite.io. We can help. For our reference, here is the trace of the error: Traceback (most recent call last): File "/home/worker/Halite/apiserver/worker/compiler.py", line 66, in nukeglob os.unlink(path) PermissionError: [Errno 13] Permission denied: './delorean/__pycache__/dates.cpython-36.pyc' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "worker.py", line 127, in executeCompileTask language, more_errors = compiler.compile_anything(temp_dir) File "/home/worker/Halite/apiserver/worker/compiler.py", line 605, in compile_anything compiled, errors = compile_function(detected_language, bot_dir, timelimit) File "/home/worker/Halite/apiserver/worker/compiler.py", line 533, in compile_function nukeglob(glob) File "/home/worker/Halite/apiserver/worker/compiler.py", line 68, in nukeglob if e.errno != errno.ENOENT and e.errno != EACCES: NameError: name 'EACCES' is not defined
--

**Comment by lidavidm** [comment]
The PR I just submitted addresses that (I noticed that too, that was due to
a typo on my part).

**Comment by j-clap** [comment]
Resubmitted after PR push, same error :/

**Comment by lidavidm** [comment]
The workers seem to still have the old worker code.

**Comment by j-clap** [comment]
Fixed
